#设置端口号
server:
  port: 7111
#设置服务端注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.25.20.127:8085/eureka/
#为服务起个名字
spring:
  application:
    name: community
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://172.25.20.127:3306/schoolyard?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      host: 172.25.20.127 # Redis服务器的ip地址
      port: 6379
      database: 0
      jedis:
        pool:
        #连接池最大连接数（使用负值表示没有限制）
          max-active: 50
          max-idle: 20
          min-idle: 2
mybatis:
  mapper-locations: classpath:com/qhit/*/dao/*Mapper.xml


